version: "3.7"
services:
  employee-manager-backend:
    image: employee-manager-backend:latest
    build: ./employee-manager-backend
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
  mariadb:
    image: "mariadb:10.5.9"
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
  employee-manager-app:
    image: employee-manager-app:latest
    container_name: employee-manager-app
    build: ./employee-manager-app/app
    depends_on: 
      - employee-manager-backend
    volumes:
      - './employee-manager-app/app:/employee-manager-app'
    ports:
      - '8888:80'